apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default

configMapGenerator:
- name: notebook-controller-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: airgapRegistry
  objref:
    kind: ConfigMap
    name: notebook-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY

configurations:
- params.yaml

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: $(airgapRegistry)public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newTag: v1.3.0-rc.1
