apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxnet-operator
spec:
  template:
    spec:
      containers:
      - name: mxnet-operator
        command:
        - /opt/kubeflow/mxnet-operator.v1

